### ISSUE TITLE
Fails in multi-module projects

### ISSUE THREAD

**Issue by mrollo** [RobWin/jgitflow-gradle-plugin#12]
If I attempt to use this plugin in multiple module projects (featureStart, releaseStart, etc.) it fails because it tells git to create the new feature/release branch for as many modules as there are in the project. Git then errors out when trying to create a branch that already exists:

```
$ ./gradlew featureStart -PfeatureName=test-feature
Incremental java compilation is an incubating feature.
:libraryone:featureStart
:librarytwo:featureStart FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':librarytwo:featureStart'.
> com.atlassian.jgitflow.core.exception.LocalBranchExistsException: local branch 'feature/test-feature' already exists
```

**Comment by RobWin** [comment]
Hi, 
where did you add the plugin?
In the root project or in a subproject section?

**Comment by mrollo** [comment]
Thanks for the fast response @RobWin 

My project's root build.gradle:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'io.github.robwin:jgitflow-gradle-plugin:0.3.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

subprojects {
    apply plugin: 'io.github.robwin.jgitflow'
}

allprojects {
    repositories {
        jcenter()
    }
}

```

**Comment by RobWin** [comment]
Could you please try to apply the plugin on the root and not inside of the allprojects and subprojects closures.

**Comment by mrollo** [comment]
That worked - thank you. I see that your documentation did specify to do this. I think I was following the pattern of another project and missed this in your docs.

**Comment by RobWin** [comment]
No problem. If it works for you, feel free to close the issue.

**Comment by RobWin** [comment]
If you like the plugin, I would love to get your GitHub star.

**Comment by mrollo** [comment]
Done and done.
