### ISSUE TITLE
No option to disable pushing commits in releaseFinish task

### ISSUE THREAD

**Issue by mrollo** [RobWin/jgitflow-gradle-plugin#13]
The maven jgitflow plugin has the option to disable pushing commits when a release is finished. This is useful when running the task in a CI system such as Jenkins where we cannot expose the credentials needed to do the push. 

If I were to submit a Pull Request that added the feature to disable pushing commits at the end of a releaseFinish task, would you be open to this? I'd make sure this maintained backwards compatibility; if "pushRelease" is not specified by the user, the plugin would push the commits by default.

**Comment by RobWin** [comment]
Hi, Yes. You can create a PR if you like.

**Comment by mrollo** [comment]
@RobWin I submitted the PR. I was debating whether or not this should be release 0.4.0 or 0.3.3... felt more like a new feature than a bug fix, so I went with 0.4.0. Obviously, let me know if you'd prefer something different.

**Comment by RobWin** [comment]
Do you plan to add more features or should I release 0.4.0?

**Comment by mrollo** [comment]
@RobWin I have no plans to add more features at this time. Thank you for being open to change and  allowing me to contribute!

**Comment by RobWin** [comment]
V0.4.0 has been released
