### ISSUE TITLE
TransportException when run releaseFinish 

### ISSUE THREAD

**Issue by jiamengyu** [RobWin/jgitflow-gradle-plugin#19]
I am trying to leverage this plugin for Gitflow/gradle to support our SpringBoot applications releases, unfortunately I am keep getting error "401 Authorization Required"  when I run releaseFinish.
I do have correct gitUsername and gitPassword configured in ~/.gradle/gradle.properties file.
===Error Message==============
Caused by: org.eclipse.jgit.api.errors.TransportException: https://<mygithub.host.name/path/project>.git: 401 Authorization Required
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:79)

Is this a known issue, or there is something I missed? Is there any  extra configuration required for JGit component from eclipse?

Thanks a lot if you can help.

**Comment by RobWin** [comment]
Hi,

no, It's not a known issue. What happens when your start the task with `-PgitUsername=<username> -PgitPassword=<password>`.
Does it work then?

**Comment by jiamengyu** [comment]
I do not want to expose Password on command line, but I did the small change in gradle script and it worked, reassign the username/password value from gradle.properties file to ext:
project.ext.set('gitUserName', project.property("gitUsername") )
project.ext.set('gitPassword', project.property("gitPassword") )

Only thing it blocks me is it doesn't delete remote release branch when I run releaseFinish task.  but it is not related to this issue.    This issue  can be closed.
